spring:
  datasource:
    url: jdbc:mysql://175.178.129.168:7219/test?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: "!01888Abc"
  redis:
    host: 110.42.214.75
    port: 6379
    password: dyt15918781398
  data:
    mongodb:
      uri: mongodb://awei:Daxiangmuc1@8.130.109.13:27017/firstDb